env:
  global:
  - REPO=d1ablorus/caddy

services:
- docker

script:
- docker build -t $REPO .;
- echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
- docker push $REPO;
- docker rmi -f $REPO;
